name: Release Please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-24.04
    steps:
      - name: Release Please
        uses: googleapis/release-please-action@16a9c90856f42705d54a6fda1823352bdc62cf38 # v4
        id: release
        with:
          target-branch: main

      - name: Checkout
        if: ${{ steps.release.outputs.release_created }}
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6

      - name: Restore
        if: ${{ steps.release.outputs.release_created }}
        uses: ./.github/actions/restore

      - name: Build
        if: ${{ steps.release.outputs.release_created }}
        run: pnpm build

      - name: Migrate
        if: ${{ steps.release.outputs.release_created }}
        env:
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        run: |
          pnpm wrangler d1 migrations apply \
            solid-pages-production \
            --env production \
            --remote

      - name: Deploy
        if: ${{ steps.release.outputs.release_created }}
        env:
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        run: >
          pnpm wrangler pages deploy
          --branch production
          --commit-hash ${GITHUB_SHA}
          --commit-message "[${GITHUB_SHA::7}] ${{ github.event.head_commit.message }}"

      - name: End-to-End
        if: ${{ steps.release.outputs.release_created }}
        uses: ./.github/actions/e2e
        env:
          BASE_URL: https://solid-pages.phi.ag
